package com.example.transleter;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;

public class StartActivity extends AppCompatActivity {
    private SharedPreferences pref;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_start);
        pref = getSharedPreferences("myPref", MODE_PRIVATE);
        SharedPreferences.Editor editor = pref.edit();
        Intent i = new Intent(StartActivity.this, MainActivity.class);

        if (pref.contains("first")){
            startActivity(i);
        }else {
            editor.putBoolean("first", true);
            editor.putString("машина", "https://media.spreadthesign.com/video/mp4/12/345841.mp4");
            editor.putString("ад", "https://media.spreadthesign.com/video/mp4/12/349210.mp4");
            editor.putString("адрес", "https://media.spreadthesign.com/video/mp4/12/4380.mp4");
            editor.putString("азия", "https://media.spreadthesign.com/video/mp4/12/351481.mp4");
            editor.putString("америка", "https://media.spreadthesign.com/video/mp4/12/349176.mp4");
            editor.putString("англия", "https://media.spreadthesign.com/video/mp4/12/16122.mp4");
            editor.putString("аромат", "https://media.spreadthesign.com/video/mp4/12/349232.mp4");
            editor.putString("африка", "https://media.spreadthesign.com/video/mp4/12/12723.mp4");
            editor.putString("бедный", "https://media.spreadthesign.com/video/mp4/12/16849.mp4");
            editor.putString("бейгел", "https://media.spreadthesign.com/video/mp4/12/349195.mp4");
            editor.putString("беларусь", "https://media.spreadthesign.com/video/mp4/12/351482.mp4");
            editor.putString("близнецы", "https://media.spreadthesign.com/video/mp4/12/14376.mp4");
            editor.putString("богатый", "https://media.spreadthesign.com/video/mp4/12/16852.mp4");
            editor.putString("болгария", "https://media.spreadthesign.com/video/mp4/12/443579.mp4");
            editor.putString("брат", "https://media.spreadthesign.com/video/mp4/12/345840.mp4");
            editor.putString("брюки", "https://media.spreadthesign.com/video/mp4/12/14784.mp4");
            editor.putString("бумага", "https://media.spreadthesign.com/video/mp4/12/12946.mp4");
            editor.putString("бутерброд", "https://media.spreadthesign.com/video/mp4/12/11336.mp4");
            editor.putString("бюстгальтер", "https://media.spreadthesign.com/video/mp4/12/14943.mp4");
            editor.putString("венгрия", "https://media.spreadthesign.com/video/mp4/12/43659.mp4");
            editor.putString("весна", "https://media.spreadthesign.com/video/mp4/12/13246.mp4");
            editor.putString("вечер", "https://media.spreadthesign.com/video/mp4/12/5574.mp4");
            editor.putString("вода", "https://media.spreadthesign.com/video/mp4/12/12530.mp4");
            editor.putString("вонять", "https://media.spreadthesign.com/video/mp4/12/349218.mp4");
            editor.putString("вопрос", "https://media.spreadthesign.com/video/mp4/12/18183.mp4");
            editor.putString("воскресенье", "https://media.spreadthesign.com/video/mp4/12/4288.mp4");
            editor.putString("время", "https://media.spreadthesign.com/video/mp4/12/4463.mp4");
            editor.putString("вторник", "https://media.spreadthesign.com/video/mp4/12/17366.mp4");
            editor.putString("вчера", "https://media.spreadthesign.com/video/mp4/12/4214.mp4");
            editor.putString("выживать", "https://media.spreadthesign.com/video/mp4/12/349219.mp4");
            editor.putString("германия", "https://media.spreadthesign.com/video/mp4/12/351484.mp4");
            editor.putString("гитара", "https://media.spreadthesign.com/video/mp4/12/349240.mp4");
            editor.putString("глухой", "https://media.spreadthesign.com/video/mp4/12/4047.mp4");
            editor.putString("глухота", "https://media.spreadthesign.com/video/mp4/12/349201.mp4");
            editor.putString("год", "https://media.spreadthesign.com/video/mp4/12/5297.mp4");
            editor.putString("голландия", "https://media.spreadthesign.com/video/mp4/12/443644.mp4");
            editor.putString("город", "https://media.spreadthesign.com/video/mp4/12/4049.mp4");
            editor.putString("горшок", "https://media.spreadthesign.com/video/mp4/12/10826.mp4");
            editor.putString("греция", "https://media.spreadthesign.com/video/mp4/12/16013.mp4");
            editor.putString("грустный", "https://media.spreadthesign.com/video/mp4/12/14670.mp4");
            editor.putString("губа", "https://media.spreadthesign.com/video/mp4/12/349231.mp4");
            editor.putString("дания", "https://media.spreadthesign.com/video/mp4/12/15709.mp4");
            editor.putString("двоюродной брат", "https://media.spreadthesign.com/video/mp4/12/14329.mp4");
            editor.putString("двоюродная сестра", "https://media.spreadthesign.com/video/mp4/12/14329.mp4");
            editor.putString("девочка", "https://media.spreadthesign.com/video/mp4/12/4105.mp4");
            editor.putString("день рождения", "https://media.spreadthesign.com/video/mp4/12/18681.mp4");
            editor.putString("дерево", "https://media.spreadthesign.com/video/mp4/12/39508.mp4");
            editor.putString("джем", "https://media.spreadthesign.com/video/mp4/12/9641.mp4");
            editor.putString("динозавр", "https://media.spreadthesign.com/video/mp4/12/349198.mp4");
            editor.putString("дискотека", "https://media.spreadthesign.com/video/mp4/12/43571.mp4");
            editor.putString("дом", "https://media.spreadthesign.com/video/mp4/12/349172.mp4");
            editor.putString("домашнее животное", "https://media.spreadthesign.com/video/mp4/12/349216.mp4");
            editor.putString("друг", "https://media.spreadthesign.com/video/mp4/12/351476.mp4");
            editor.putString("духовка", "https://media.spreadthesign.com/video/mp4/12/349181.mp4");
            editor.putString("душиться", "https://media.spreadthesign.com/video/mp4/12/349215.mp4");
            editor.putString("благоухать", "https://media.spreadthesign.com/video/mp4/12/349215.mp4");
            editor.putString("пахнуть приятно", "https://media.spreadthesign.com/video/mp4/12/349215.mp4");
            editor.putString("пахнуть", "https://media.spreadthesign.com/video/mp4/12/349215.mp4");
            editor.putString("дядя", "https://media.spreadthesign.com/video/mp4/12/14306.mp4");
            editor.putString("Египет", "https://media.spreadthesign.com/video/mp4/12/349189.mp4");
            editor.putString("еда", "https://media.spreadthesign.com/video/mp4/12/9110.mp4");
            editor.putString("есть", "https://media.spreadthesign.com/video/mp4/12/8842.mp4");
            editor.putString("жестовый язык", "https://media.spreadthesign.com/video/mp4/12/6184.mp4");
            editor.putString("жечь", "https://media.spreadthesign.com/video/mp4/12/7692.mp4");
            editor.putString("гореть", "https://media.spreadthesign.com/video/mp4/12/7692.mp4");
            editor.putString("жёлтый", "https://media.spreadthesign.com/video/mp4/12/5776.mp4");
            editor.putString("забота", "https://media.spreadthesign.com/video/mp4/12/27049.mp4");
            editor.putString("завтра", "https://media.spreadthesign.com/video/mp4/12/4186.mp4");
            editor.putString("завтрак", "https://media.spreadthesign.com/video/mp4/12/4316.mp4");
            editor.putString("здоровье", "https://media.spreadthesign.com/video/mp4/12/27606.mp4");
            editor.putString("зебра", "https://media.spreadthesign.com/video/mp4/12/43103.mp4");
            editor.putString("зелёный", "https://media.spreadthesign.com/video/mp4/12/5717.mp4");
            editor.putString("зима", "https://media.spreadthesign.com/video/mp4/12/13275.mp4");
            editor.putString("зубная боль", "https://media.spreadthesign.com/video/mp4/12/349243.mp4");
            editor.putString("болит зуб", "https://media.spreadthesign.com/video/mp4/12/349243.mp4");
            editor.putString("зубы", "https://media.spreadthesign.com/video/mp4/12/349242.mp4");
            editor.putString("зуб", "https://media.spreadthesign.com/video/mp4/12/349242.mp4");
            editor.putString("известный", "https://media.spreadthesign.com/video/mp4/12/23004.mp4");
            editor.putString("израиль", "https://media.spreadthesign.com/video/mp4/12/349180.mp4");
            editor.putString("имя", "https://media.spreadthesign.com/video/mp4/12/4027.mp4");
            editor.putString("индия", "https://media.spreadthesign.com/video/mp4/12/349212.mp4");
            editor.putString("интернет", "https://media.spreadthesign.com/video/mp4/12/4695.mp4");
            editor.putString("иордания", "https://media.spreadthesign.com/video/mp4/12/349226.mp4");
            //
            editor.putString("япония", "https://media.spreadthesign.com/video/mp4/12/43688.mp4");
            editor.putString("я", "https://media.spreadthesign.com/video/mp4/12/12788.mp4");
            editor.putString("юмор глухих", "https://media.spreadthesign.com/video/mp4/12/349230.mp4");
            editor.putString("юбка", "https://media.spreadthesign.com/video/mp4/12/14812.mp4");
            editor.putString("эстония", "https://media.spreadthesign.com/video/mp4/12/349190.mp4");
            editor.putString("экран", "https://media.spreadthesign.com/video/mp4/12/44584.mp4");
            editor.putString("щека", "https://media.spreadthesign.com/video/mp4/12/16353.mp4");
            editor.putString("шляпа", "https://media.spreadthesign.com/video/mp4/12/14863.mp4");
            editor.putString("школа", "https://media.spreadthesign.com/video/mp4/12/12914.mp4");
            editor.putString("шея", "https://media.spreadthesign.com/video/mp4/12/349187.mp4");
            editor.putString("швеция", "https://media.spreadthesign.com/video/mp4/12/443682.mp4");
            editor.putString("швейцария", "https://media.spreadthesign.com/video/mp4/12/443691.mp4");
            editor.putString("что", "https://media.spreadthesign.com/video/mp4/12/43119.mp4");
            editor.putString("чистый", "https://media.spreadthesign.com/video/mp4/12/8103.mp4");
            editor.putString("чехол", "https://media.spreadthesign.com/video/mp4/12/349241.mp4");
            editor.putString("четверг", "https://media.spreadthesign.com/video/mp4/12/4265.mp4");
            editor.putString("черный", "https://media.spreadthesign.com/video/mp4/12/345820.mp45");
            editor.putString("церковь глухих", "https://media.spreadthesign.com/video/mp4/12/349237.mp4");
            editor.putString("целоваться", "https://media.spreadthesign.com/video/mp4/12/351493.mp4");
            editor.putString("цветок", "https://media.spreadthesign.com/video/mp4/12/13929.mp4");
            editor.putString("хэллоуин", "https://media.spreadthesign.com/video/mp4/12/349194.mp4");
            editor.putString("хороший", "https://media.spreadthesign.com/video/mp4/12/349239.mp4");
            editor.putString("толковый", "https://media.spreadthesign.com/video/mp4/12/349239.mp4");
            editor.putString("ходить", "https://media.spreadthesign.com/video/mp4/12/16689.mp4");
            editor.putString("франция", "https://media.spreadthesign.com/video/mp4/12/443590.mp4");
            editor.putString("фотокамера", "https://media.spreadthesign.com/video/mp4/12/18714.mp4");
            editor.putString("фиолетовый", "https://media.spreadthesign.com/video/mp4/12/14691.mp4");
            editor.putString("финляндия", "https://media.spreadthesign.com/video/mp4/12/443589.mp4");
            editor.putString("фантастический", "https://media.spreadthesign.com/video/mp4/12/15910.mp4");
            editor.putString("потрясающий", "https://media.spreadthesign.com/video/mp4/12/15910.mp4");
            editor.putString("утро", "https://media.spreadthesign.com/video/mp4/12/5251.mp4");
            editor.putString("усталый", "https://media.spreadthesign.com/video/mp4/12/5543.mp4");
            editor.putString("украина", "https://media.spreadthesign.com/video/mp4/12/351489.mp4");
            editor.putString("удивляться", "https://media.spreadthesign.com/video/mp4/12/13973.mp4");
            editor.putString("уверенный", "https://media.spreadthesign.com/video/mp4/12/349183.mp4");
            editor.putString("тётя", "https://media.spreadthesign.com/video/mp4/12/14316.mp4");
            editor.putString("тетя", "https://media.spreadthesign.com/video/mp4/12/14316.mp4");
            editor.putString("тёмный", "https://media.spreadthesign.com/video/mp4/12/5471.mp4");
            editor.putString("темный", "https://media.spreadthesign.com/video/mp4/12/5471.mp4");
            editor.putString("ты", "https://media.spreadthesign.com/video/mp4/12/12804.mp4");
            editor.putString("турция", "https://media.spreadthesign.com/video/mp4/12/449772.mp4");
            editor.putString("труба", "https://media.spreadthesign.com/video/mp4/12/351492.mp4");
            editor.putString("трава", "https://media.spreadthesign.com/video/mp4/12/19250.mp4");
            editor.putString("торт на день рождение", "https://media.spreadthesign.com/video/mp4/12/349169.mp4");
            editor.putString("торт", "https://media.spreadthesign.com/video/mp4/12/349169.mp4");
            editor.putString("темнота", "https://media.spreadthesign.com/video/mp4/12/349236.mp4");
            editor.putString("тело", "https://media.spreadthesign.com/video/mp4/12/349166.mp4");
            editor.putString("телефон", "https://media.spreadthesign.com/video/mp4/12/13844.mp4");
            editor.putString("тв", "https://media.spreadthesign.com/video/mp4/12/18015.mp4");
            editor.putString("телевидение", "https://media.spreadthesign.com/video/mp4/12/18015.mp4");
            editor.putString("танцевать", "https://media.spreadthesign.com/video/mp4/12/349202.mp4");
            editor.putString("талия", "https://media.spreadthesign.com/video/mp4/12/349184.mp4");
            editor.putString("считывать с губ", "https://media.spreadthesign.com/video/mp4/12/18062.mp4");
            editor.putString("счастливый", "https://media.spreadthesign.com/video/mp4/12/14660.mp4");
            editor.putString("сурдлимпиада", "https://media.spreadthesign.com/video/mp4/12/349188.mp4");
            editor.putString("сумочка", "https://media.spreadthesign.com/video/mp4/12/349207.mp4");
            editor.putString("сумка", "https://media.spreadthesign.com/video/mp4/12/7127.mp4");
            editor.putString("сумасшедший", "https://media.spreadthesign.com/video/mp4/12/349200.mp4");
            editor.putString("суббота", "https://media.spreadthesign.com/video/mp4/12/4282.mp4");
            editor.putString("ступня", "https://media.spreadthesign.com/video/mp4/12/349186.mp4");
            editor.putString("стул", "https://media.spreadthesign.com/video/mp4/12/7905.mp4");
            editor.putString("странный", "https://media.spreadthesign.com/video/mp4/12/349175.mp4");
            editor.putString("страна", "https://media.spreadthesign.com/video/mp4/12/6204.mp4");
            editor.putString("станция", "https://media.spreadthesign.com/video/mp4/12/28197.mp4");
            editor.putString("вокзал", "https://media.spreadthesign.com/video/mp4/12/28197.mp4");
            editor.putString("среда", "https://media.spreadthesign.com/video/mp4/12/4254.mp4");
            editor.putString("соревнование", "https://media.spreadthesign.com/video/mp4/12/27117.mp4");
            editor.putString("сообщество глухих", "https://media.spreadthesign.com/video/mp4/12/349229.mp4");
            editor.putString("сон", "https://media.spreadthesign.com/video/mp4/12/5369.mp4");
            editor.putString("солнце", "https://media.spreadthesign.com/video/mp4/12/17058.mp4");
            editor.putString("собрание", "https://media.spreadthesign.com/video/mp4/12/5419.mp4");
            editor.putString("собака", "https://media.spreadthesign.com/video/mp4/12/13431.mp4");
            editor.putString("смысл", "https://media.spreadthesign.com/video/mp4/12/18082.mp4");
            editor.putString("смеяться", "https://media.spreadthesign.com/video/mp4/12/17579.mp4");
            editor.putString("смех", "https://media.spreadthesign.com/video/mp4/12/17579.mp4");
            editor.putString("смелый", "https://media.spreadthesign.com/video/mp4/12/349167.mp4");
            editor.putString("плечо", "https://media.spreadthesign.com/video/mp4/12/349235.mp4");
            editor.putString("плохой", "https://media.spreadthesign.com/video/mp4/12/14620.mp4");
            editor.putString("поезд", "https://media.spreadthesign.com/video/mp4/12/5617.mp4");
            editor.putString("полет", "https://media.spreadthesign.com/video/mp4/12/26547.mp4");
            editor.putString("польша", "https://media.spreadthesign.com/video/mp4/12/443663.mp4");
            editor.putString("помощь", "https://media.spreadthesign.com/video/mp4/12/2098.mp4");
            editor.putString("понедельник", "https://media.spreadthesign.com/video/mp4/12/4227.mp4");
            editor.putString("португалия", "https://media.spreadthesign.com/video/mp4/12/16882.mp4");
            editor.putString("поцелуй", "https://media.spreadthesign.com/video/mp4/12/17549.mp4");
            editor.putString("почему", "https://media.spreadthesign.com/video/mp4/12/5194.mp4");
            editor.putString("почтовый ящик", "https://media.spreadthesign.com/video/mp4/12/349213.mp4");
            editor.putString("президент", "https://media.spreadthesign.com/video/mp4/12/349244.mp4");
            editor.putString("премия", "https://media.spreadthesign.com/video/mp4/12/349179.mp4");
            editor.putString("приветствовать", "https://media.spreadthesign.com/video/mp4/12/351494.mp4");
            editor.putString("проклинать", "https://media.spreadthesign.com/video/mp4/12/351478.mp4");
            editor.putString("просматривать", "https://media.spreadthesign.com/video/mp4/12/349199.mp4");
            editor.putString("пролистывать", "https://media.spreadthesign.com/video/mp4/12/349199.mp4");
            editor.putString("пузырек", "https://media.spreadthesign.com/video/mp4/12/349168.mp4");
            editor.putString("путешествовать", "https://media.spreadthesign.com/video/mp4/12/6287.mp4");
            editor.putString("пятница", "https://media.spreadthesign.com/video/mp4/12/4267.mp4");
            editor.putString("работа", "https://media.spreadthesign.com/video/mp4/12/349238.mp4");
            editor.putString("рай", "https://media.spreadthesign.com/video/mp4/12/295852.mp4");
            editor.putString("ребёнок", "https://media.spreadthesign.com/video/mp4/12/16508.mp4");
            editor.putString("родной язык", "https://media.spreadthesign.com/video/mp4/12/105994.mp4");
            editor.putString("родственные отношения", "https://media.spreadthesign.com/video/mp4/12/18244.mp4");
            editor.putString("рождество", "https://media.spreadthesign.com/video/mp4/12/43629.mp4");
            editor.putString("розовый", "https://media.spreadthesign.com/video/mp4/12/14688.mp4");
            editor.putString("россия", "https://media.spreadthesign.com/video/mp4/12/443665.mp4");
            editor.putString("рот", "https://media.spreadthesign.com/video/mp4/12/15321.mp4");
            editor.putString("рубашка", "https://media.spreadthesign.com/video/mp4/12/14749.mp4");
            editor.putString("левая рука", "https://media.spreadthesign.com/video/mp4/12/295878.mp4");
            editor.putString("правая рука", "https://media.spreadthesign.com/video/mp4/12/295877.mp4");
            editor.putString("румыния", "https://media.spreadthesign.com/video/mp4/12/43741.mp4");
            editor.putString("ручка", "https://media.spreadthesign.com/video/mp4/12/12916.mp4");
            editor.putString("ручной багаж", "https://media.spreadthesign.com/video/mp4/12/30178.mp4");
            editor.putString("рыба", "https://media.spreadthesign.com/video/mp4/12/9033.mp4");
            editor.putString("с нарушением слуха", "https://media.spreadthesign.com/video/mp4/12/295885.mp4");
            editor.putString("сан марино", "https://media.spreadthesign.com/video/mp4/12/351486.mp4");
            editor.putString("светлый", "https://media.spreadthesign.com/video/mp4/12/23412.mp4");
            editor.putString("свой парень", "https://media.spreadthesign.com/video/mp4/12/12755.mp4");
            editor.putString("своя подруга", "https://media.spreadthesign.com/video/mp4/12/12773.mp4");
            editor.putString("сегодня", "https://media.spreadthesign.com/video/mp4/12/4204.mp4");
            editor.putString("сестра", "https://media.spreadthesign.com/video/mp4/12/345888.mp4");
            editor.putString("синий", "https://media.spreadthesign.com/video/mp4/12/345834.mp4");
            editor.putString("слепоглухой", "https://media.spreadthesign.com/video/mp4/12/43634.mp4");
            editor.putString("слепой", "https://media.spreadthesign.com/video/mp4/12/43635.mp4");
            editor.putString("словакия", "https://media.spreadthesign.com/video/mp4/12/43091.mp4");
            editor.putString("словения", "https://media.spreadthesign.com/video/mp4/12/351487.mp4");
            editor.putString("слуховой аппарат", "https://media.spreadthesign.com/video/mp4/12/295922.mp4");
            editor.putString("слышащий", "https://media.spreadthesign.com/video/mp4/12/12884.mp4");
            editor.putString("красный", "https://media.spreadthesign.com/video/mp4/12/4495.mp4");
            editor.putString("кричать", "https://media.spreadthesign.com/video/mp4/12/43707.mp4");
            editor.putString("кровь", "https://media.spreadthesign.com/video/mp4/12/349177.mp4");
            editor.putString("культура глухих", "https://media.spreadthesign.com/video/mp4/12/349196.mp4");
            editor.putString("лампа", "https://media.spreadthesign.com/video/mp4/12/6080.mp4");
            editor.putString("латвия", "https://media.spreadthesign.com/video/mp4/12/349214.mp4");
            editor.putString("лексикон", "https://media.spreadthesign.com/video/mp4/12/294918.mp4");
            editor.putString("лето", "https://media.spreadthesign.com/video/mp4/12/13247.mp4");
            editor.putString("лексикон", "https://media.spreadthesign.com/video/mp4/12/294918.mp4");
            editor.putString("латвия", "https://media.spreadthesign.com/video/mp4/12/349214.mp4");
            editor.putString("лампа", "https://media.spreadthesign.com/video/mp4/12/6080.mp4");
            editor.putString("культура глухих", "https://media.spreadthesign.com/video/mp4/12/349196.mp4");
            editor.putString("кровь", "https://media.spreadthesign.com/video/mp4/12/349177.mp4");
            editor.putString("кричать", "https://media.spreadthesign.com/video/mp4/12/43707.mp4");
            editor.putString("красный", "https://media.spreadthesign.com/video/mp4/12/4495.mp4");
            editor.putString("кошка", "https://media.spreadthesign.com/video/mp4/12/13448.mp4");
            editor.putString("коричневый", "https://media.spreadthesign.com/video/mp4/12/7655.mp4");
            editor.putString("компьютер", "https://media.spreadthesign.com/video/mp4/12/13778.mp4");
            editor.putString("колбаса", "https://media.spreadthesign.com/video/mp4/12/11394.mp4");
            editor.putString("когда", "https://media.spreadthesign.com/video/mp4/12/4723.mp4");
            editor.putString("книга", "https://media.spreadthesign.com/video/mp4/12/18692.mp4");
            editor.putString("китай", "https://media.spreadthesign.com/video/mp4/12/349178.mp4");
            editor.putString("картофель", "https://media.spreadthesign.com/video/mp4/12/10853.mp4");
            editor.putString("картинка", "https://media.spreadthesign.com/video/mp4/12/13830.mp4");
            editor.putString("канун нового года", "https://media.spreadthesign.com/video/mp4/12/349227.mp4");
            editor.putString("италия", "https://media.spreadthesign.com/video/mp4/12/443619.mp4");
            editor.putString("испуганный", "https://media.spreadthesign.com/video/mp4/12/43584.mp4");
            editor.putString("испания", "https://media.spreadthesign.com/video/mp4/12/443680.mp4");
            editor.putString("исландия", "https://media.spreadthesign.com/video/mp4/12/43669.mp4");
            editor.putString("ирландия", "https://media.spreadthesign.com/video/mp4/12/16144.mp4");
            editor.putString("1 миллион", "https://media.spreadthesign.com/video/mp4/12/313442.mp4");
            editor.putString("миллион", "https://media.spreadthesign.com/video/mp4/12/313442.mp4");
            editor.putString("1000000", "https://media.spreadthesign.com/video/mp4/12/313442.mp4");
            editor.putString("добро пожаловать", "https://media.spreadthesign.com/video/mp4/12/18420.mp4");
            editor.putString("позвонить на сервис", "https://media.spreadthesign.com/video/mp4/12/134844.mp4");
            editor.putString("Пока", "https://media.spreadthesign.com/video/mp4/12/100036.mp4");
            editor.putString("с днем рождения", "https://media.spreadthesign.com/video/mp4/12/295884.mp4");
            editor.putString("очень быстро бежать", "https://media.spreadthesign.com/video/mp4/12/315295.mp4");
            editor.putString("быстро бежать", "https://media.spreadthesign.com/video/mp4/12/315295.mp4");
            editor.putString("беспощадно", "https://media.spreadthesign.com/video/mp4/12/315844.mp4");
            editor.putString("будет сделано", "https://media.spreadthesign.com/video/mp4/12/18542.mp4");
            editor.putString("быть звездой", "https://media.spreadthesign.com/video/mp4/12/315301.mp4");
            editor.putString("время от времени", "https://media.spreadthesign.com/video/mp4/12/318933.mp4");
            editor.putString("вызывать отвращение", "https://media.spreadthesign.com/video/mp4/12/315918.mp4");
            editor.putString("выкинуть из головы", "https://media.spreadthesign.com/video/mp4/12/315919.mp4");
            editor.putString("забыть", "https://media.spreadthesign.com/video/mp4/12/315919.mp4");
            editor.putString("перестать думать", "https://media.spreadthesign.com/video/mp4/12/315919.mp4");
            editor.putString("выпутаться из ситуации", "https://media.spreadthesign.com/video/mp4/12/315922.mp4");
            editor.putString("говорить без умолку", "https://media.spreadthesign.com/video/mp4/12/315951.mp4");
            editor.putString("дар красноречия", "https://media.spreadthesign.com/video/mp4/12/317586.mp4");
            editor.putString("держать зуб на кого-либо", "https://media.spreadthesign.com/video/mp4/12/315973.mp4");
            editor.putString("желать причинить вред", "https://media.spreadthesign.com/video/mp4/12/315973.mp4");
            editor.putString("желать отомстить", "https://media.spreadthesign.com/video/mp4/12/315973.mp4");
            editor.putString("желать зла", "https://media.spreadthesign.com/video/mp4/12/315973.mp4");
            editor.putString("держать себя в руках", "https://media.spreadthesign.com/video/mp4/12/133763.mp4");
            editor.putString("закадычные друзья", "https://media.spreadthesign.com/video/mp4/12/315300.mp4");
            editor.putString("не разлей вода", "https://media.spreadthesign.com/video/mp4/12/315300.mp4");
            editor.putString("избежать обвинения", "https://media.spreadthesign.com/video/mp4/12/316055.mp4");
            editor.putString("избежать наказания", "https://media.spreadthesign.com/video/mp4/12/316055.mp4");
            editor.putString("кроватка", "https://media.spreadthesign.com/video/mp4/12/315764.mp4");
            editor.putString("Легок на помине", "https://media.spreadthesign.com/video/mp4/12/315696.mp4");
            editor.putString("действовать решительно", "https://media.spreadthesign.com/video/mp4/12/316363.mp4");
            editor.putString("ой", "https://media.spreadthesign.com/video/mp4/12/229246.mp4");
            editor.putString("осадить", "https://media.spreadthesign.com/video/mp4/12/316468.mp4");
            editor.putString("пойман с поличным", "https://media.spreadthesign.com/video/mp4/12/316826.mp4");
            editor.putString("потерять связь", "https://media.spreadthesign.com/video/mp4/12/315716.mp4");
            editor.putString("развлекаться", "https://media.spreadthesign.com/video/mp4/12/19278.mp4");
            editor.putString("скользкий пол", "https://media.spreadthesign.com/video/mp4/12/135135.mp4");
            editor.putString("слава богу", "https://media.spreadthesign.com/video/mp4/12/321197.mp4");
            editor.putString("спасти в последний момент", "https://media.spreadthesign.com/video/mp4/12/135174.mp4");
            editor.putString("счастливого пути", "https://media.spreadthesign.com/video/mp4/12/227221.mp4");
            editor.putString("только для взрослых", "https://media.spreadthesign.com/video/mp4/12/99592.mp4");
            editor.putString("тсс", "https://media.spreadthesign.com/video/mp4/12/112180.mp4");
            editor.putString("уйти из жизни", "https://media.spreadthesign.com/video/mp4/12/136691.mp4");
            editor.putString("ура", "https://media.spreadthesign.com/video/mp4/12/99634.mp4");
            editor.putString("хранить в тайне", "https://media.spreadthesign.com/video/mp4/12/315750.mp4");
            editor.putString("хранить секрет", "https://media.spreadthesign.com/video/mp4/12/315750.mp4");
            editor.putString("чуть-чуть", "https://media.spreadthesign.com/video/mp4/12/317274.mp4");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.putString("", "");
            editor.apply();
            startActivity(i);
        }
    }
}